DROP TABLE IF EXISTS "product_image";
DROP TABLE IF EXISTS "review_image";
DROP TABLE IF EXISTS "item_in_order";
DROP TABLE IF EXISTS "product_has_tag";
DROP TABLE IF EXISTS "order";
DROP TABLE IF EXISTS "review";
DROP TABLE IF EXISTS "product";
DROP TABLE IF EXISTS "shop";
DROP TABLE IF EXISTS "user";
DROP TABLE IF EXISTS "tag";
DROP TABLE IF EXISTS "image";

--CREATE TYPE role_types AS ENUM ('user', 'seller', 'admin');

-- image table: id, path, alt_text, width, height
CREATE TABLE IF NOT EXISTS "image" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "path" varchar NOT NULL,
  "alt_text" varchar NOT NULL,
  "width" INT,
  "height" INT
);

-- user table: id, name, pfp, join_date
CREATE TABLE IF NOT EXISTS "user" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar NOT NULL,
  "pfp" INT NOT NULL,
  "join_date" date NOT NULL,
  "email" varchar NOT NULL,
  "password_hash" varchar NOT NULL,
  "role" role_types NOT NULL
);

ALTER TABLE "user" ALTER "role" SET DEFAULT CAST ('user' AS role_types);

-- shop table: id, name, manager, banner, location
CREATE TABLE IF NOT EXISTS "shop" (
  "id" INT PRIMARY KEY NOT NULL,
  "name" varchar NOT NULL,
  "manager" INT NOT NULL,
  "banner" INT NOT NULL,
  "location" varchar
);

-- product table: id, name, shop, price, listed_at, description
CREATE TABLE IF NOT EXISTS "product" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar NOT NULL,
  "shop" INT NOT NULL,
  "price" decimal NOT NULL,
  "listed_at" date NOT NULL,
  "description" varchar NOT NULL
);

-- review table: id, reviewer, product, title, content, rating, posted_at
CREATE TABLE IF NOT EXISTS "review" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "reviewer" INT NOT NULL,
  "product" INT NOT NULL,
  "title" varchar NOT NULL,
  "content" varchar NOT NULL,
  "rating" decimal,
  "posted_at" date NOT NULL
);

-- order table: id, seller, buyer, payed_at
CREATE TABLE IF NOT EXISTS "order" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "seller" INT NOT NULL,
  "buyer" INT NOT NULL,
  "payed_at" date
);

-- tag table: id, title
CREATE TABLE IF NOT EXISTS "tag" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "title" varchar NOT NULL
);

-- product_image joiner table: product, image
CREATE TABLE IF NOT EXISTS "product_image" (
  "product" INT NOT NULL,
  "image" INT NOT NULL,
  PRIMARY KEY ("product", "image")
);

-- review_image joiner table: review, image
CREATE TABLE IF NOT EXISTS "review_image" (
  "review" INT NOT NULL,
  "image" INT NOT NULL,
  PRIMARY KEY ("image", "review")
);

-- item_in_order joiner table: product, order, quantity
CREATE TABLE IF NOT EXISTS "item_in_order" (
  "product" INT NOT NULL,
  "order" INT NOT NULL,
  "quantity" INT NOT NULL DEFAULT 1,
  PRIMARY KEY ("product", "order")
);

-- product_has_tag joiner table: product, tag
CREATE TABLE IF NOT EXISTS "product_has_tag" (
  "product" INT NOT NULL,
  "tag" INT NOT NULL,
  PRIMARY KEY ("product", "tag")
);

-- foreign key indexs
CREATE INDEX IF NOT EXISTS "fk_pfp" ON "user" ("pfp");
CREATE INDEX IF NOT EXISTS "fk_banner" ON "shop" ("banner");
CREATE INDEX IF NOT EXISTS "fk_manager" ON "shop" ("manager");
CREATE INDEX IF NOT EXISTS "fk_shop_prod" ON "product" ("shop");
CREATE INDEX IF NOT EXISTS "fk_reviewer" ON "review" ("reviewer");
CREATE INDEX IF NOT EXISTS "fk_reviewed" ON "review" ("product");
CREATE INDEX IF NOT EXISTS "fk_prod_img_prod" ON "product_image" ("product");
CREATE INDEX IF NOT EXISTS "fk_prod_img_img" ON "product_image" ("image");
CREATE INDEX IF NOT EXISTS "fk_rev_img_rev" ON "review_image" ("review");
CREATE INDEX IF NOT EXISTS "fk_rev_img_img" ON "review_image" ("image");
CREATE INDEX IF NOT EXISTS "fk_order_seller" ON "order" ("seller");
CREATE INDEX IF NOT EXISTS "fk_order_buyer" ON "order" ("buyer");
CREATE INDEX IF NOT EXISTS "fk_order_prod" ON "item_in_order" ("product");
CREATE INDEX IF NOT EXISTS "fk_order_prod_prder" ON "item_in_order" ("order");
CREATE INDEX IF NOT EXISTS "fk_prod_tag_tag" ON "product_has_tag" ("tag");
CREATE INDEX IF NOT EXISTS "fk_prod_tag_prod" ON "product_has_tag" ("product");

-- foreign keys
ALTER TABLE "user" ADD CONSTRAINT "fk_pfp" FOREIGN KEY ("pfp") REFERENCES "image" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE "shop" ADD CONSTRAINT "fk_banner" FOREIGN KEY ("banner") REFERENCES "image" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE "shop" ADD CONSTRAINT "fk_manager" FOREIGN KEY ("manager") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE "product" ADD CONSTRAINT "fk_shop_prod" FOREIGN KEY ("shop") REFERENCES "shop" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE "review" ADD CONSTRAINT "fk_reviewer" FOREIGN KEY ("reviewer") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE "review" ADD CONSTRAINT "fk_reviewed" FOREIGN KEY ("product") REFERENCES "product" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE "product_image" ADD CONSTRAINT "fk_prod_img_prod" FOREIGN KEY ("product") REFERENCES "product" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE "product_image" ADD CONSTRAINT "fk_prod_img_img" FOREIGN KEY ("image") REFERENCES "image" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE "review_image" ADD CONSTRAINT "fk_rev_img_rev" FOREIGN KEY ("review") REFERENCES "review" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE "review_image" ADD CONSTRAINT "fk_rev_img_img" FOREIGN KEY ("image") REFERENCES "image" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE "order" ADD CONSTRAINT "fk_order_seller" FOREIGN KEY ("seller") REFERENCES "shop" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE "order" ADD CONSTRAINT "fk_order_buyer" FOREIGN KEY ("buyer") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE "item_in_order" ADD CONSTRAINT "fk_order_prod" FOREIGN KEY ("product") REFERENCES "product" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE "item_in_order" ADD CONSTRAINT "fk_order_prod_prder" FOREIGN KEY ("order") REFERENCES "order" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE "product_has_tag" ADD CONSTRAINT "fk_prod_tag_prod" FOREIGN KEY ("product") REFERENCES "product" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE "product_has_tag" ADD CONSTRAINT "fk_prod_tag_tag" FOREIGN KEY ("tag") REFERENCES "tag" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;
