import postgres from 'postgres';
import placeholderData from '@/app/seed/placeholder-data';
const {image, item_in_order, order, product, product_has_tag, product_image, review, review_image, shop, tag, user} = placeholderData;
const sql = postgres(process.env.POSTGRESS_URL!, { ssl: 'require' });

async function seedImage() {
  await sql`
    CREATE TABLE IF NOT EXISTS "image" (
      "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
      "path" varchar NOT NULL,
      "alt_text" varchar NOT NULL,
      "width" INT,
      "height" INT
    );`;
  const insertionResult = await Promise.all(image.map(item => sql`
    INSERT INTO "image" (id, width, height, path, alt_text)
    VALUES (${item.id}, ${item.width}, ${item.height}, ${item.path}, ${item.alt_text})
    ON CONFLICT(id) DO NOTHING;
  `));
  return insertionResult;
}
async function seedUser() {
  await sql`
    CREATE TABLE IF NOT EXISTS "user" (
      "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
      "name" varchar NOT NULL,
      "pfp" INT NOT NULL,
      "join_date" date NOT NULL
    );`;
  const insertionResult = await Promise.all(user.map(item => sql`
    INSERT INTO "user" (id, name, join_date, pfp)
    VALUES (${item.id}, ${item.name}, ${item.join_date}, ${item.pfp})
    ON CONFLICT(id) DO NOTHING;`));
  return insertionResult;
}
async function seedShop() {
  await sql`
    CREATE TABLE IF NOT EXISTS "shop" (
      "id" INT PRIMARY KEY NOT NULL,
      "name" varchar NOT NULL,
      "manager" INT NOT NULL,
      "banner" INT NOT NULL,
      "location" varchar
    );`;
  const insertionResult = await Promise.all(shop.map(item => sql`
    INSERT INTO "shop" (id, manager, location, name, banner)
    VALUES (${item.id}, ${item.manager}, ${item.location}, ${item.name}, ${item.banner})
    ON CONFLICT(id) DO NOTHING;`));
  return insertionResult;
}
async function seedTag() {
  await sql`
    CREATE TABLE IF NOT EXISTS "tag" (
      "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
      "title" varchar NOT NULL
    );`;
  const insertionResult = await Promise.all(tag.map(item => sql`
    INSERT INTO "tag" (id, title)
    VALUES (${item.id}, ${item.title})
    ON CONFLICT(id) DO NOTHING;`));
  return insertionResult;
}
async function seedOrder() {
  await sql`
    CREATE TABLE IF NOT EXISTS "order" (
      "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
      "seller" INT NOT NULL,
      "buyer" INT NOT NULL,
      "amount" decimal NOT NULL,
      "payed_at" date
    );`;
  const insertionResult = await Promise.all(order.map(item => sql`
    INSERT INTO "order" (id, buyer, seller, payed_at, amount)
    VALUES (${item.id}, ${item.buyer}, ${item.seller}, ${item.payed_at}, ${item.amount})
    ON CONFLICT(id) DO NOTHING;`));
  return insertionResult;
}
async function seedProduct() {
  await sql`
CREATE TABLE IF NOT EXISTS "product" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar NOT NULL,
  "shop" INT NOT NULL,
  "price" decimal NOT NULL,
  "listed_at" date NOT NULL
);`;
  const insertionResult = await Promise.all(product.map(item => sql`
    INSERT INTO "product" (id, shop, name, price, listed_at)
    VALUES (${item.id}, ${item.shop}, ${item.name}, ${item.price}, ${item.listed_at})
    ON CONFLICT(id) DO NOTHING;`));
  return insertionResult;
}
async function seedReview() {
  await sql`
CREATE TABLE IF NOT EXISTS "review" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "reviewer" INT NOT NULL,
  "product" INT NOT NULL,
  "title" varchar NOT NULL,
  "content" varchar NOT NULL,
  "rating" decimal,
  "posted_at" date NOT NULL
);`;
  const insertionResult = await Promise.all(review.map(item => sql`
    INSERT INTO "review" ("id", "reviewer", "product", "title", "content", "rating", "posted_at")
    VALUES (${item.id}, ${item.reviewer}, ${item.product}, ${item.title}, ${item.content}, ${item.rating}, ${item.posted_at})
    ON CONFLICT(id) DO NOTHING;`));
  return insertionResult;
}
async function seedProductTag() {
  await sql`
    CREATE TABLE IF NOT EXISTS "product_has_tag" (
      "product" INT NOT NULL,
      "tag" INT NOT NULL,
      PRIMARY KEY ("product", "tag")
    );`;
  const insertionResult = await Promise.all(product_has_tag.map(item => sql`
    INSERT INTO "product_has_tag" (product, tag)
    VALUES (${item.product}, ${item.tag})
    ON CONFLICT(product, tag) DO NOTHING;`));
  return insertionResult;
}
async function seedProductOrder() {
  await sql`
    CREATE TABLE IF NOT EXISTS "item_in_order" (
      "product" INT NOT NULL,
      "order" INT NOT NULL,
      "quantity" INT NOT NULL DEFAULT 1,
      PRIMARY KEY ("product", "order")
    );`;
  const insertionResult = await Promise.all(item_in_order.map(item => sql`
    INSERT INTO "item_in_order" ("order", product, quantity)
    VALUES (${item.order}, ${item.product}, ${item.quantity})
    ON CONFLICT("order", "product") DO NOTHING;`));
  return insertionResult;
}
async function seedReviewImage() {
  await sql`
    CREATE TABLE IF NOT EXISTS "review_image" (
      "review" INT NOT NULL,
      "image" INT NOT NULL,
      PRIMARY KEY ("image", "review")
    );`;
  const insertionResult = await Promise.all(review_image.map(item => sql`
    INSERT INTO "review_image" (review, image)
    VALUES (${item.review}, ${item.image})
    ON CONFLICT(review, image) DO NOTHING;`));
  return insertionResult;
}
async function seedProductImage() {
  await sql`
    CREATE TABLE IF NOT EXISTS "product_image" (
      "product" INT NOT NULL,
      "image" INT NOT NULL,
      PRIMARY KEY ("product", "image")
    );`;
  const insertionResult = await Promise.all(product_image.map(item => sql`
    INSERT INTO "product_image" (product, image)
    VALUES (${item.product}, ${item.image})
    ON CONFLICT(product, image) DO NOTHING;`));
  return insertionResult;
}

export async function GET() {
  if(process.env.NODE_ENV === 'production' || process.env.NODE_ENV !== 'development')
    return Response.json({message: 'Seeding the database may only be done in a sevelopment environment'});

  try {
    await sql.begin(sql => [
      seedImage(),
      seedUser(),
      seedShop(),
      seedTag(),
      seedProduct(),
      seedReview(),
      seedOrder(),
      seedProductTag(),
      seedProductImage(),
      seedReviewImage(),
      seedProductOrder()
    ]);
    return Response.json({message: 'Database seeded'});
  } catch (e) {
    console.log(e);
    return Response.json({message: 'Database seeding failed. It can take a few tries.', error: e}, {status: 500});
  }
}